CUDA_VISIBLE_DEVICES=0 python test_original_gp.py\
 --scale 1\
 --ps 1 --ps_scale 2\
 --real 1\
 --mode MC\
 --color 1\
 --output_map 0\
 --zeroout 0 --keep_ind 0\
 --num_of_layers 20\
 --delog logs/logs_color_MC_AWGN_RVIN\
 --cond 1 --refine 0 --refine_opt 1\
 --test_noise_level 75 0 0 0 0 0 --ext_test_noise_level 35\
 --test_data cropped_beijing\
 --test_data_gnd Nam_mean\
 --out_dir results/original_DnCNN/cropped_beijing_result
